runnable 类的run（）方法不抛出异常和没有返回值

callable 类的call() throw Exception方法会抛出异常，
         还可以通过Futuretask类进行返回值操作。
